import type { InstrumentDefinition } from "./types";

/**
 * Bocatto steel-string acoustic family. Models and options come from the
 * luthier's spreadsheet ("Violões Aço"); option images come from the official
 * reference pack (public/refs, generated by scripts/build-refs.mjs). The whole
 * creation flow, summary and PDF are driven by this data — adding nylon
 * guitars, electric guitars, basses or violas later means creating a sibling
 * file (e.g. `violaoNylon`, `guitarra`, `baixo`, `viola`) and registering it
 * in `instruments` below, with no screen changes.
 */
export const violaoAco: InstrumentDefinition = {
  id: "violao-aco",
  family: "violao-aco",
  name: { pt: "Violão de Aço", en: "Steel-string guitar" },
  strings: "aco",

  models: [
    {
      id: "om",
      name: "Bocatto OM",
      scale: "645 mm",
      image: "/refs/modelos/om.webp",
      description: {
        pt: "Corpo Orchestra Model, equilibrado e articulado — favorito do dedilhado.",
        en: "Orchestra Model body, balanced and articulate — a fingerstyle favorite.",
      },
      characteristics: [
        { pt: "Escala 645 mm", en: "645 mm scale" },
        { pt: "Médio porte, muito confortável", en: "Mid-size, very comfortable" },
        { pt: "Resposta equilibrada e definida", en: "Balanced, defined response" },
      ],
    },
    {
      id: "dreadnought",
      name: "Bocatto Dreadnought",
      scale: "645 mm",
      image: "/refs/modelos/dreadnought.webp",
      description: {
        pt: "Corpo amplo de graves profundos e grande projeção — ideal para palhetada.",
        en: "Big body with deep lows and strong projection — ideal for strumming.",
      },
      characteristics: [
        { pt: "Escala 645 mm", en: "645 mm scale" },
        { pt: "Graves potentes e volume", en: "Powerful lows and volume" },
        { pt: "Clássico do violão de aço", en: "The steel-string classic" },
      ],
    },
    {
      id: "jumbo",
      name: "Bocatto Jumbo",
      scale: "645 mm",
      image: "/refs/modelos/jumbo.webp",
      description: {
        pt: "O maior dos corpos, som cheio e ressonante com presença máxima.",
        en: "The largest body, full resonant sound with maximum presence.",
      },
      characteristics: [
        { pt: "Escala 645 mm", en: "645 mm scale" },
        { pt: "Volume e sustain generosos", en: "Generous volume and sustain" },
        { pt: "Presença marcante no palco", en: "Striking stage presence" },
      ],
    },
    {
      id: "j45",
      name: "Bocatto J45",
      scale: "645 mm",
      image: "/refs/modelos/j45.webp",
      description: {
        pt: "Ombros arredondados, timbre quente e equilibrado — voz de cantor e compositor.",
        en: "Round shoulders, warm balanced tone — the singer-songwriter voice.",
      },
      characteristics: [
        { pt: "Escala 645 mm", en: "645 mm scale" },
        { pt: "Médios quentes e encorpados", en: "Warm, full mids" },
        { pt: "Ótimo para voz e violão", en: "Great for voice and guitar" },
      ],
    },
    {
      id: "015",
      name: "Bocatto 015",
      scale: "628 mm",
      image: "/refs/modelos/015.webp",
      description: {
        pt: "Corpo menor de escala curta, timbre íntimo e focado, muito confortável.",
        en: "Smaller short-scale body, intimate focused tone, very comfortable.",
      },
      characteristics: [
        { pt: "Escala 628 mm (curta)", en: "628 mm (short) scale" },
        { pt: "Resposta imediata e doce", en: "Immediate, sweet response" },
        { pt: "Conforto para tocar por horas", en: "Comfortable for hours of play" },
      ],
    },
    {
      id: "mini",
      name: "Bocatto Mini",
      scale: "577 mm",
      image: "/refs/modelos/mini.webp",
      description: {
        pt: "Compacto de escala curta, leve e fácil de tocar — perfeito para viagem.",
        en: "Compact short-scale, light and easy to play — perfect for travel.",
      },
      characteristics: [
        { pt: "Escala 577 mm (curta)", en: "577 mm (short) scale" },
        { pt: "Leve e portátil", en: "Light and portable" },
        { pt: "Tocabilidade fácil", en: "Easy playability" },
      ],
    },
  ],

  /* One category per stage — the reference photo is the protagonist. */
  steps: [
    {
      id: "tampo",
      title: { pt: "Tampo", en: "Top" },
      intro: {
        pt: "A voz do instrumento nasce aqui: o tampo define o caráter do som.",
        en: "The instrument's voice is born here: the top defines the character of the sound.",
      },
      fields: [
        {
          kind: "choice",
          id: "tampo",
          label: { pt: "Madeira do tampo", en: "Top wood" },
          required: true,
          allowOther: true,
          options: [
            { id: "sitka", label: { pt: "Sitka Spruce", en: "Sitka spruce" }, image: "/refs/tampo/sitka.webp" },
            { id: "abeto-alemao", label: { pt: "Abeto Alemão", en: "German spruce" }, image: "/refs/tampo/abeto-alemao.webp" },
            { id: "red-cedar", label: { pt: "Red Cedar", en: "Red cedar" }, image: "/refs/tampo/red-cedar.webp" },
            { id: "mogno", label: { pt: "Mogno", en: "Mahogany" }, image: "/refs/tampo/mogno.webp" },
          ],
        },
      ],
    },
    {
      id: "fundo",
      title: { pt: "Fundo", en: "Back" },
      intro: {
        pt: "O fundo reflete e colore o som projetado pelo tampo.",
        en: "The back reflects and colors the sound projected by the top.",
      },
      fields: [
        {
          kind: "choice",
          id: "fundo",
          label: { pt: "Madeira do fundo", en: "Back wood" },
          required: true,
          allowOther: true,
          options: [
            { id: "jacaranda", label: { pt: "Jacarandá", en: "Rosewood (Jacarandá)" }, image: "/refs/fundo/jacaranda.webp" },
            { id: "mogno", label: { pt: "Mogno", en: "Mahogany" }, image: "/refs/fundo/mogno.webp" },
            { id: "maple", label: { pt: "Maple", en: "Maple" }, image: "/refs/fundo/maple.webp" },
            { id: "imbuia", label: { pt: "Imbuia", en: "Imbuia" }, image: "/refs/fundo/imbuia.webp" },
          ],
        },
      ],
    },
    {
      id: "lateral",
      title: { pt: "Lateral", en: "Sides" },
      intro: {
        pt: "As laterais completam a caixa acústica — tradicionalmente na mesma madeira do fundo.",
        en: "The sides complete the sound box — traditionally in the same wood as the back.",
      },
      fields: [
        {
          kind: "choice",
          id: "lateral",
          label: { pt: "Madeira das laterais", en: "Sides wood" },
          required: true,
          allowOther: true,
          options: [
            { id: "jacaranda", label: { pt: "Jacarandá", en: "Rosewood (Jacarandá)" }, image: "/refs/lateral/jacaranda.webp" },
            { id: "mogno", label: { pt: "Mogno", en: "Mahogany" }, image: "/refs/lateral/mogno.webp" },
            { id: "maple", label: { pt: "Maple", en: "Maple" }, image: "/refs/lateral/maple.webp" },
            { id: "imbuia", label: { pt: "Imbuia", en: "Imbuia" }, image: "/refs/lateral/imbuia.webp" },
          ],
        },
      ],
    },
    {
      id: "braco",
      title: { pt: "Braço", en: "Neck" },
      intro: {
        pt: "Estabilidade e conforto: a madeira do braço acompanha cada nota tocada.",
        en: "Stability and comfort: the neck wood follows every note you play.",
      },
      fields: [
        {
          kind: "choice",
          id: "braco",
          label: { pt: "Madeira do braço", en: "Neck wood" },
          allowOther: true,
          options: [
            { id: "mogno", label: { pt: "Mogno", en: "Mahogany" }, image: "/refs/braco/mogno.webp" },
            { id: "cedro", label: { pt: "Cedro", en: "Cedar" }, image: "/refs/braco/cedro.webp" },
            { id: "maple", label: { pt: "Maple", en: "Maple" }, image: "/refs/braco/maple.webp" },
            { id: "marupa", label: { pt: "Marupá", en: "Marupá" }, image: "/refs/braco/marupa.webp" },
          ],
        },
      ],
    },
    {
      id: "escala",
      title: { pt: "Escala", en: "Fretboard" },
      intro: {
        pt: "Onde os dedos vivem: densidade e textura que definem o toque.",
        en: "Where your fingers live: density and texture that define the feel.",
      },
      fields: [
        {
          kind: "choice",
          id: "escala",
          label: { pt: "Madeira da escala", en: "Fretboard wood" },
          allowOther: true,
          options: [
            { id: "ebano", label: { pt: "Ébano", en: "Ebony" }, image: "/refs/escala/ebano.webp" },
            { id: "jacaranda", label: { pt: "Jacarandá", en: "Rosewood (Jacarandá)" }, image: "/refs/escala/jacaranda.webp" },
            { id: "pau-ferro", label: { pt: "Pau Ferro", en: "Pau ferro" }, image: "/refs/escala/pau-ferro.webp" },
            { id: "maple", label: { pt: "Maple", en: "Maple" }, image: "/refs/escala/maple.webp" },
            { id: "black-purple", label: { pt: "Black Purple", en: "Black Purple" }, image: "/refs/escala/black-purple.webp" },
          ],
        },
      ],
    },
    {
      id: "cavalete",
      title: { pt: "Cavalete", en: "Bridge" },
      intro: {
        pt: "A ponte entre as cordas e o tampo — transmite cada vibração.",
        en: "The bridge between strings and top — it transmits every vibration.",
      },
      fields: [
        {
          kind: "choice",
          id: "cavalete",
          label: { pt: "Madeira do cavalete", en: "Bridge wood" },
          allowOther: true,
          options: [
            { id: "ebano", label: { pt: "Ébano", en: "Ebony" }, image: "/refs/cavalete/ebano.webp" },
            { id: "jacaranda", label: { pt: "Jacarandá", en: "Rosewood (Jacarandá)" }, image: "/refs/cavalete/jacaranda.webp" },
            { id: "pau-ferro", label: { pt: "Pau Ferro", en: "Pau ferro" }, image: "/refs/cavalete/pau-ferro.webp" },
            { id: "black-purple", label: { pt: "Black Purple", en: "Black Purple" }, image: "/refs/cavalete/black-purple.webp" },
          ],
        },
      ],
    },
    {
      id: "roseta",
      title: { pt: "Roseta", en: "Rosette" },
      intro: {
        pt: "A assinatura ao redor da boca — artesanato em miniatura.",
        en: "The signature around the soundhole — craftsmanship in miniature.",
      },
      fields: [
        {
          kind: "choice",
          id: "roseta",
          label: { pt: "Estilo da roseta", en: "Rosette style" },
          allowOther: true,
          options: [
            { id: "jacaranda-exclusiva", label: { pt: "Jacarandá Exclusiva", en: "Exclusive rosewood" }, image: "/refs/roseta/jacaranda-exclusiva.webp" },
            { id: "abalone", label: { pt: "Abalone", en: "Abalone" }, image: "/refs/roseta/abalone.webp" },
            { id: "madre-perola", label: { pt: "Madrepérola", en: "Mother-of-pearl" }, image: "/refs/roseta/madre-perola.webp" },
          ],
        },
      ],
    },
    {
      id: "marcacao",
      title: { pt: "Marcação da Escala", en: "Fretboard Markers" },
      intro: {
        pt: "Os pontos de referência que guiam a mão — discretos ou ornamentados.",
        en: "The reference points that guide your hand — discreet or ornate.",
      },
      fields: [
        {
          kind: "choice",
          id: "marcacao",
          label: { pt: "Estilo da marcação", en: "Marker style" },
          allowOther: true,
          options: [
            { id: "dots-6mm", label: { pt: "Dots 6 mm", en: "6 mm dots" }, image: "/refs/marcacao/dots-6mm.webp" },
            { id: "cruz-losango", label: { pt: "Cruz e Losango (padrão Martin)", en: "Cross & Diamond (Martin style)" }, image: "/refs/marcacao/cruz-losango.webp" },
            { id: "floral", label: { pt: "Floral", en: "Floral" }, image: "/refs/marcacao/floral.webp" },
          ],
        },
      ],
    },
    {
      id: "escudo",
      title: { pt: "Escudo", en: "Pickguard" },
      intro: {
        pt: "Proteção do tampo com personalidade — ou a beleza da madeira nua.",
        en: "Top protection with personality — or the beauty of bare wood.",
      },
      fields: [
        {
          kind: "choice",
          id: "escudo",
          label: { pt: "Estilo do escudo", en: "Pickguard style" },
          allowOther: true,
          options: [
            { id: "gota-tortoise", label: { pt: "Gota Tortoise", en: "Teardrop Tortoise" }, image: "/refs/escudo/gota-tortoise.webp" },
            { id: "gota-preto", label: { pt: "Gota Preto", en: "Teardrop Black" }, image: "/refs/escudo/gota-preto.webp" },
            { id: "gota-madeira", label: { pt: "Gota em Madeira", en: "Teardrop Wood" }, image: "/refs/escudo/gota-madeira.webp" },
            { id: "hummingbird-tortoise", label: { pt: "Hummingbird Tortoise", en: "Hummingbird Tortoise" }, image: "/refs/escudo/hummingbird-tortoise.webp" },
            { id: "hummingbird-preto", label: { pt: "Hummingbird Preto", en: "Hummingbird Black" }, image: "/refs/escudo/hummingbird-preto.webp" },
            { id: "hummingbird-madeira", label: { pt: "Hummingbird em Madeira", en: "Hummingbird Wood" }, image: "/refs/escudo/hummingbird-madeira.webp" },
            { id: "sem-escudo", label: { pt: "Sem escudo", en: "No pickguard" }, image: "/refs/escudo/sem-escudo.webp" },
          ],
        },
      ],
    },
    {
      id: "cutaway",
      title: { pt: "Cutaway", en: "Cutaway" },
      intro: {
        pt: "Acesso livre às notas mais agudas — ou a silhueta clássica completa.",
        en: "Free access to the highest notes — or the full classic silhouette.",
      },
      fields: [
        {
          kind: "choice",
          id: "cutaway",
          label: { pt: "Estilo do cutaway", en: "Cutaway style" },
          allowOther: true,
          options: [
            { id: "sem-cutaway", label: { pt: "Sem cutaway", en: "No cutaway" }, image: "/refs/cutaway/sem-cutaway.webp" },
            { id: "veneziano", label: { pt: "Veneziano (arredondado)", en: "Venetian (rounded)" }, image: "/refs/cutaway/veneziano.webp" },
            { id: "florentino", label: { pt: "Florentino (agudo)", en: "Florentine (pointed)" }, image: "/refs/cutaway/florentino.webp" },
          ],
        },
      ],
    },
    {
      id: "tarraxas",
      title: { pt: "Tarraxas", en: "Tuners" },
      intro: {
        pt: "Precisão de afinação e o brilho do metal no headstock.",
        en: "Tuning precision and the gleam of metal on the headstock.",
      },
      fields: [
        {
          kind: "choice",
          id: "tarraxas",
          label: { pt: "Marca das tarraxas", en: "Tuner brand" },
          allowOther: true,
          options: [
            { id: "gotoh", label: { pt: "Gotoh", en: "Gotoh" }, image: "/refs/tarraxas/gotoh.webp" },
            { id: "grover", label: { pt: "Grover", en: "Grover" }, image: "/refs/tarraxas/grover.webp" },
            { id: "guyker", label: { pt: "Guyker", en: "Guyker" }, image: "/refs/tarraxas/guyker.webp" },
          ],
        },
        {
          kind: "choice",
          id: "tarraxasAcabamento",
          label: { pt: "Acabamento das tarraxas", en: "Tuner finish" },
          allowOther: true,
          options: [
            { id: "cromo", label: { pt: "Cromo", en: "Chrome" }, swatch: "#c0c0c0" },
            { id: "black", label: { pt: "Black", en: "Black" }, swatch: "#222222" },
            { id: "gold", label: { pt: "Gold", en: "Gold" }, swatch: "#c9a227" },
            { id: "cosmo-black", label: { pt: "Cosmo Black", en: "Cosmo Black" }, swatch: "#3a3a3a" },
          ],
        },
      ],
    },
    {
      id: "nutRastilho",
      title: { pt: "Nut e Rastilho", en: "Nut & Saddle" },
      intro: {
        pt: "Pequenos no tamanho, enormes no som: onde as cordas tocam o instrumento.",
        en: "Small in size, huge in sound: where the strings meet the instrument.",
      },
      fields: [
        {
          kind: "choice",
          id: "nutRastilho",
          label: { pt: "Material do nut e rastilho", en: "Nut & saddle material" },
          allowOther: true,
          options: [
            { id: "nature-bone", label: { pt: "Nature Bone (osso)", en: "Nature Bone (bone)" }, image: "/refs/nutRastilho/nature-bone.webp" },
            { id: "grafitech", label: { pt: "Graphtech", en: "Graphtech" }, image: "/refs/nutRastilho/grafitech.webp" },
            { id: "sintetico", label: { pt: "Sintético (plástico)", en: "Synthetic (plastic)" }, image: "/refs/nutRastilho/sintetico.webp" },
          ],
        },
      ],
    },
    {
      id: "trastes",
      title: { pt: "Trastes", en: "Frets" },
      intro: {
        pt: "O metal sob os dedos — durabilidade e suavidade em cada bend.",
        en: "The metal under your fingers — durability and smoothness in every bend.",
      },
      fields: [
        {
          kind: "choice",
          id: "trastes",
          label: { pt: "Marca e liga dos trastes", en: "Fret brand & alloy" },
          allowOther: true,
          options: [
            { id: "sanko-gotoh-liga", label: { pt: "Sanko Gotoh — Liga", en: "Sanko Gotoh — Alloy" }, image: "/refs/trastes/sanko-gotoh-liga.webp" },
            { id: "jescar-inox", label: { pt: "Jescar — Inox", en: "Jescar — Stainless" }, image: "/refs/trastes/jescar-inox.webp" },
            { id: "dhp-liga", label: { pt: "DHP — Liga", en: "DHP — Alloy" }, image: "/refs/trastes/dhp-liga.webp" },
            { id: "dhp-inox", label: { pt: "DHP — Inox", en: "DHP — Stainless" }, image: "/refs/trastes/dhp-inox.webp" },
          ],
        },
        {
          kind: "choice",
          id: "trastesTamanho",
          label: { pt: "Tamanho dos trastes", en: "Fret size" },
          allowOther: true,
          options: [
            { id: "medio", label: { pt: "Médio", en: "Medium" } },
            { id: "medio-jumbo", label: { pt: "Médio Jumbo", en: "Medium Jumbo" } },
            { id: "jumbo", label: { pt: "Jumbo", en: "Jumbo" } },
          ],
        },
      ],
    },
    {
      id: "armRest",
      title: { pt: "Arm Rest", en: "Arm Rest" },
      intro: {
        pt: "Conforto de tocar por horas: o chanfro que abraça o seu braço.",
        en: "Comfort for hours of playing: the bevel that embraces your arm.",
      },
      fields: [
        {
          kind: "choice",
          id: "armRest",
          label: { pt: "Arm Rest", en: "Arm rest" },
          allowOther: true,
          options: [
            { id: "arm-rest-madeira", label: { pt: "Com Arm Rest em madeira", en: "With wood arm rest" }, image: "/refs/armRest/arm-rest-madeira.webp" },
            { id: "sem-arm-rest", label: { pt: "Sem Arm Rest", en: "No arm rest" }, image: "/refs/armRest/sem-arm-rest.webp" },
          ],
        },
      ],
    },
    {
      id: "acabamento",
      title: { pt: "Acabamento", en: "Finish" },
      intro: {
        pt: "A última camada: como a madeira encontra a luz.",
        en: "The final layer: how the wood meets the light.",
      },
      fields: [
        {
          kind: "choice",
          id: "acabamento",
          label: { pt: "Acabamento do verniz", en: "Finish sheen" },
          allowOther: true,
          options: [
            { id: "brilho", label: { pt: "Brilho", en: "Gloss" }, image: "/refs/acabamento/brilho.webp" },
            { id: "semi-brilho", label: { pt: "Semi Brilho", en: "Semi-gloss" }, image: "/refs/acabamento/semi-brilho.webp" },
            { id: "fosco", label: { pt: "Fosco", en: "Matte" }, image: "/refs/acabamento/fosco.webp" },
          ],
        },
      ],
    },
    {
      id: "detalhes",
      title: { pt: "Detalhes Técnicos", en: "Technical Details" },
      intro: {
        pt: "Os ajustes finais de construção — headstock, tensor e captação.",
        en: "The final construction details — headstock, truss rod and pickup.",
      },
      fields: [
        {
          kind: "choice",
          id: "headstock",
          label: { pt: "Headstock", en: "Headstock" },
          allowOther: true,
          options: [
            { id: "modelo-1", label: { pt: "Modelo I", en: "Model I" } },
            { id: "modelo-2", label: { pt: "Modelo II", en: "Model II" } },
            { id: "modelo-3", label: { pt: "Modelo III", en: "Model III" } },
            { id: "modelo-4", label: { pt: "Modelo IV", en: "Model IV" } },
            { id: "modelo-5", label: { pt: "Modelo V", en: "Model V" } },
          ],
        },
        {
          kind: "choice",
          id: "tensor",
          label: { pt: "Tensor", en: "Truss rod" },
          allowOther: true,
          options: [
            { id: "dupla-acao", label: { pt: "Dupla ação", en: "Dual action" } },
            { id: "acao-simples", label: { pt: "Ação simples", en: "Single action" } },
            { id: "vintage", label: { pt: "Vintage", en: "Vintage" } },
            { id: "sem-tensor", label: { pt: "Sem tensor", en: "No truss rod" } },
          ],
        },
        {
          kind: "choice",
          id: "captacao",
          label: { pt: "Captação", en: "Pickup" },
          allowOther: true,
          options: [
            {
              id: "fornecida-cliente",
              label: {
                pt: "Fornecida pelo cliente (instalação inclusa)",
                en: "Provided by the customer (installation included)",
              },
            },
            { id: "sem-captacao", label: { pt: "Sem captação", en: "No pickup" } },
          ],
        },
      ],
    },
  ],
};

/** Registry of instrument families. Add nylon/guitarra/baixo/viola here later. */
export const instruments = { "violao-aco": violaoAco } as const;

/** Default family used by the creation flow while only steel guitars exist. */
export const defaultInstrument = violaoAco;

// Backwards-compatible alias (older imports).
export const violao = violaoAco;
